collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3742052705492824
  brandStrength: 0.5451128
  lightness: 0.8487226122524589
  brandColors:
    - '#FFF9E9'
    - '#0A0B0D'
    - '#DEB36C'
    - '#4C4531'
    - '#1CA59E'
  rhythmicContrast: 0.9023541398346424
typography_spectrum: 0.2080831311177462
layout_spectrum: 0.9403866
name: Defendering
