collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8361976
  brandStrength: 0.5451128
  lightness: 0.2013963
  brandColors:
    - '#FFF9E9'
    - '#0A0B0D'
    - '#DEB36C'
    - '#4C4531'
    - '#1CA59E'
  rhythmicContrast: 0.982277
typography_spectrum: 0.2080831311177462
layout_spectrum: 0.2722878
name: Defendering
